# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

r_github_packages:
  - gaborcsardi/debugme
  - MangoTheCat/processx
  - MangoTheCat/webdriver

matrix:
  include:
    - os: linux
      r: oldrel
      compiler: gcc
    - os: linux
      r: release
      compiler: gcc
    - os: linux
      r: devel
      compiler: gcc
    - os: osx
      r: oldrel
      compiler: clang
    - os: osx
      r: release
      compiler: clang
  
after_success:
  - Rscript -e 'covr::codecov()'
  
